---
title: Bewegen in de scèneweergave
hero_image: images/banner.png
description: Bewegen in de scèneweergave
version: 4
listed: false
copyedit: false
last_tested: "2021-10-19"
steps:
  - title: Bewegen in de scèneweergave
