---
title: Moving in the Scene view
hero_image: images/banner.png
description: Moving in the Scene view
version: 4
listed: false
copyedit: false
last_tested: "2021-10-19"
steps:
  - 
    title: Moving in the Scene view
