---
title: Moverse en la Vista de escena
hero_image: images/banner.png
description: Moverse en la Vista de escena
version: 4
listed: false
copyedit: false
last_tested: "2021-10-19"
steps:
  - title: Moverse en la Vista de escena
