---
title: Déplacement dans la vue Scene
hero_image: images/banner.png
description: Déplacement dans la vue Scene
version: 4
listed: false
copyedit: false
last_tested: "2021-10-19"
steps:
  - title: Déplacement dans la vue Scene
